<?php
// Start the session
session_start();

// Check if user is logged in
if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}

// Include database connection
require_once 'config/database.php';
$database = new Database();
$db = $database->getConnection();

// Get user data
$user_id = $_SESSION['user_id'];
$query = "SELECT first_name, last_name, email FROM users WHERE id = :id";
$stmt = $db->prepare($query);
$stmt->bindParam(":id", $user_id);
$stmt->execute();
$user = $stmt->fetch(PDO::FETCH_ASSOC);

// Include FPDF library
require('fpdf/fpdf.php');

// Create new PDF document
$pdf = new FPDF();
$pdf->AddPage();

// Set document information
$pdf->SetCreator('HealthAssist Pro');
$pdf->SetAuthor('HealthAssist Pro');
$pdf->SetTitle('Health Report - ' . date('Y-m-d'));
$pdf->SetSubject('Health Report');

// Set font
$pdf->SetFont('Arial', 'B', 16);

// Title
$pdf->Cell(0, 10, 'Health Report', 0, 1, 'C');
$pdf->Ln(10);

// User Information
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(40, 10, 'Patient Name:', 0, 0);
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(0, 10, $user['first_name'] . ' ' . $user['last_name'], 0, 1);

$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(40, 10, 'Email:', 0, 0);
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(0, 10, $user['email'], 0, 1);

$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(40, 10, 'Report Date:', 0, 0);
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(0, 10, date('F j, Y'), 0, 1);

$pdf->Ln(10);

// Health Summary Section
$pdf->SetFont('Arial', 'B', 14);
$pdf->SetFillColor(200, 220, 255);
$pdf->Cell(0, 10, 'Health Summary', 0, 1, 'L', true);
$pdf->Ln(5);

// Summary Table
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(140, 10, 'Metric', 1, 0, 'L', true);
$pdf->Cell(50, 10, 'Value', 1, 1, 'C', true);

$pdf->SetFont('Arial', '', 12);
$fill = false;
$metrics = [
    'Total Symptoms Tracked' => '47',
    'Average Severity' => '2.8/5.0',
    'Most Common Symptom' => 'Headache',
    'Days Since Last Severe Symptom' => '5 Days'
];

foreach ($metrics as $metric => $value) {
    $pdf->SetFillColor($fill ? 240 : 255, 240, 255);
    $pdf->Cell(140, 10, $metric, 1, 0, 'L', true);
    $pdf->Cell(50, 10, $value, 1, 1, 'C', true);
    $fill = !$fill;
}

$pdf->Ln(10);

// Recent Symptoms Section
$pdf->SetFont('Arial', 'B', 14);
$pdf->SetFillColor(200, 220, 255);
$pdf->Cell(0, 10, 'Recent Symptoms', 0, 1, 'L', true);
$pdf->Ln(5);

// Symptoms Table
$pdf->SetFont('Arial', 'B', 11);
$pdf->Cell(40, 10, 'Date', 1, 0, 'C', true);
$pdf->Cell(40, 10, 'Symptom', 1, 0, 'C', true);
$pdf->Cell(30, 10, 'Severity', 1, 0, 'C', true);
$pdf->Cell(80, 10, 'Notes', 1, 1, 'C', true);

$pdf->SetFont('Arial', '', 10);
$fill = false;

// Sample data (replace with actual data from database)
$symptoms = [
    ['date' => 'May 30, 2023', 'name' => 'Headache', 'severity' => 'Moderate', 'notes' => 'Started in the afternoon'],
    ['date' => 'May 28, 2023', 'name' => 'Fatigue', 'severity' => 'Mild', 'notes' => 'After long day at work'],
    ['date' => 'May 25, 2023', 'name' => 'Nausea', 'severity' => 'Severe', 'notes' => 'After lunch']
];

foreach ($symptoms as $symptom) {
    $pdf->SetFillColor($fill ? 240 : 255, 240, 255);
    $pdf->Cell(40, 10, $symptom['date'], 1, 0, 'L', true);
    $pdf->Cell(40, 10, $symptom['name'], 1, 0, 'L', true);
    $pdf->Cell(30, 10, $symptom['severity'], 1, 0, 'C', true);
    $pdf->Cell(80, 10, $symptom['notes'], 1, 1, 'L', true);
    $fill = !$fill;
}

// Footer
$pdf->SetY(-30);
$pdf->SetFont('Arial', 'I', 8);
$pdf->Cell(0, 10, 'This report was generated by HealthAssist Pro on ' . date('F j, Y \a\t g:i A'), 0, 1, 'C');
$pdf->Cell(0, 5, 'For any questions, please contact our support team.', 0, 1, 'C');

// Output PDF
$pdf->Output('D', 'health_report_' . date('Y-m-d') . '.pdf');
?>
